//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public long BankCardInfoID { get; set; }
        public bool Gender { get; set; }
        public long AdressID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Adress Adress { get; set; }
        public virtual BankCardInfo BankCardInfo { get; set; }
    }
}
